---
title: "TidyR Limpieza de datos"
author: "Jorge_Faieta_Dacovich - Neoland"
date: "7/12/2020"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
```

```{r}
tableU <- read_csv("/Users/victoriasofia93/Desktop/r-basic-master/tidyverse-data-science-master/scripts/data/population.csv")
view(tableU)
```

```{r}
tableU %>% # obtener cociente casos entre poblacion
  mutate(rate = cases / population*10000)

# Si queremos calcular el número de casos
tableU %>%
  count(year, wt = cases)

# Grafico agrupado por países
tableU %>%
  ggplot(aes(year, cases)) + 
  geom_line(aes(group = country), color = "grey") + 
  geom_point(aes(color = country))
```


# Spreading (repartir, separar) y Gathering (reune)

```{r}
# Reuno las columnas, 3 parámetros: columnas o variables, nombre de la variable cuyos valores forman parte de los valores de la columna y el nombre de la variable cuyo valores están repartidos en las celdas.
table4a %>%
  gather(`1999`,`2000`, key = "year", value = "cases") -> tidy4a


table4b

table4b %>%
  gather(`1999`, `2000`, key = "year", value = "population") -> tidy4b

# Junto las tablas (tengo las mismas variables country y year)

left_join(tidy4a, tidy4b) -> tidy4


# ----------
# Spread : se utiliza cuando una observación está repartida en diferentes filas

table2

table2 %>%
  spread(key = type, value = count) 
```

# Técnica de separación:

```{r}
table3 # la columna rate tiene dos observaciones separadas por "/"

table3 %>%
  separate(rate, into = c("cases", "population"), # indico las columnas en las que quedará dividida SI ejecuto hasta aquí también me separa los valores.
           sep = "/", convert = TRUE) %>% # coloco el convert para que me convierta los datos (el que mejor infiera)
  separate(year, sep = 2, into = c("century","year"), # puedo separa también por posición
           convert = TRUE)

table5

# "UNITE" : si deseo unirlos utilizo 
table5 %>%
  unite(new_year, century, year, sep = "")

# Separe rate y uní los años que había separado
table5 %>%
  separate(rate, c("cases","population"), sep = "/") %>%
  unite(new_year, century, year, sep = "")
```
# Ejercicios

```{r}
#Ejercicio 4
roi <- tibble(
  year = c(rep(2016,4), rep(2017,4), 2018),
  quarter = c(rep(c(1,2,3,4),2),1),
  return = rnorm(9, mean = 0.5, sd = 1)
)

roi %>%
  spread(year, return) %>%
  gather("year", "return", `2016`:`2018`)

#Ejercicio 8
pregnancy <- tribble(
  ~pregnant, ~male, ~female,
  #--------|------|---------
  "yes",    NA,    32,
  "no",     85,    43
)

pregnancy %>%
  gather("male", "female", key = sex, value = count)  %>%
  mutate(pregnant = (pregnant == "yes"),
         female = (sex == "female")) %>%
  select(-sex)

roi <- tibble(
  year = c(rep(2016,4), rep(2017,4), 2018),
  quarter = c(rep(c(1,2,3,4),2),1),
  return = rnorm(9, mean = 0.5, sd = 1)
)
roi$return[7] = NA

roi %>%
  spread(year, return) %>%
  gather(year, return, `2016`:`2018`, na.rm = TRUE)
```

# data set tuberculosis y datos de las poblaciones

```{r}
tidyr::who

# Agrupo en 6 columnas o variables, nose de que va el nw_sp... espero y lo agrupo en key y se que su valor corresponde a los casos
tidyr::who %>%
  gather(new_sp_m014:newrel_f65, key = "key", value = "cases", na.rm = T) -> who1


who2 <- who1 %>%
  mutate(key = stringr::str_replace(key, "newrel", "new_rel")) # en la variable Key donde encuentres newrel sustituyela por new_rel

who3 <- who2 %>%
  separate(key, c("new", "type", "sexage"), sep = "_") # separo la columna key por los diferentes valores

who4 <- who3 %>%
  select(-new, -iso2, -iso3) # me cargo esas columnas inutiles

who5 <- who4 %>%
  separate(sexage, c("sex", "age"), sep = 1) # separare por la primera posición por la que tengo que corta

# de manera rápida:

tidyr::who %>%
  gather(new_sp_m014:newrel_f65, key = "key", value = "cases", na.rm = TRUE) %>%
  mutate(key = stringr::str_replace(key, "newrel", "new_rel")) %>%
  separate(key, c("new", "type", "sexage"), sep = "_") %>%
  select(-new, -iso2, -iso3) %>%
  separate(sexage, c("sex", "age"), sep = 1)
```

